# Dockerfile.main
FROM python:3.12.4-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY main.py data.txt ./ 
COPY Utils/ ./Utils

EXPOSE 5000

CMD ["python", "-u", "main.py"]
