# Dockerfile.Evaluator
FROM python:3.12.4-slim

WORKDIR /app


COPY Evaluator.py data.txt smallRequirements.txt ./
RUN apt-get update && apt-get install -y \
    libhdf5-dev \
    python3-dev \
    build-essential \
    libatlas-base-dev \
    gfortran \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip    
RUN pip install -r smallRequirements.txt
CMD ["python", "-u", "Evaluator.py"]
