# Dockerfile.trainer
FROM arm64v8/python:3.12.4-bookworm
WORKDIR /app

# Copy necessary files
COPY Trainer.py data.txt smallRequirements.txt ./
# Install dependencies
RUN apt-get update && apt-get install -y \
    libhdf5-dev \
    python3-dev \
    build-essential \
    libatlas-base-dev \
    gfortran \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip    
RUN pip install -r smallRequirements.txt

# Run the Trainer
CMD ["python", "-u", "Trainer.py"]

