# Dockerfile.trainer
FROM python:3.12.4-slim
WORKDIR /app

# Copy necessary files
COPY Trainer.py data.txt smallRequirements.txt ./
# Install dependencies

RUN pip install -r smallRequirements.txt

# Run the Trainer
CMD ["python", "-u", "Trainer.py"]

