# Dockerfile.evaluator
FROM python:3.12.4-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY Evaluator.py data.txt ./

CMD ["python", "Evaluator.py"]
